"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "uz" | "ru" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  uz: {
    home: "Bosh sahifa",
    menu: "Menyu",
    cart: "Savat",
    contact: "Aloqa",
    about: "Biz haqimizda",
    admin: "Admin",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    logout: "Chiqish",
    addToCart: "Savatga qo'shish",
    order: "Buyurtma berish",
    total: "Jami",
    welcome: "Milano Cafe ga xush kelibsiz",
    ourMenu: "Bizning menyu",
    specialOffers: "Maxsus takliflar",
    aboutUs: "Biz haqimizda",
    contactUs: "Biz bilan bog'laning",
    address: "Manzil",
    phone: "Telefon",
    email: "Email",
    workingHours: "Ish vaqti",
    monday: "Dushanba",
    tuesday: "Seshanba",
    wednesday: "Chorshanba",
    thursday: "Payshanba",
    friday: "Juma",
    saturday: "Shanba",
    sunday: "Yakshanba",
    orderSuccess: "Buyurtma muvaffaqiyatli yuborildi!",
    orderConfirmed: "Buyurtma tasdiqlandi",
    processing: "Tayyorlanmoqda",
    ready: "Tayyor",
    delivered: "Yetkazildi",
    quantity: "Miqdor",
    price: "Narx",
    recipe: "Retsept",
    ingredients: "Tarkib",
    name: "Ism",
    message: "Xabar",
    send: "Yuborish",
    location: "Joylashuv",
    selectLocation: "Joylashuvni tanlang",
    paymentMethod: "To'lov usuli",
    cash: "Naqd",
    card: "Karta",
    click: "Click",
    payme: "Payme",
    confirmOrder: "Buyurtmani tasdiqlash",
    orderPlaced: "Buyurtma qabul qilindi",
    thankYou: "Rahmat!",
    account: "Hisob",
    myOrders: "Mening buyurtmalarim",
    orderHistory: "Buyurtmalar tarixi",
    profile: "Profil",
    settings: "Sozlamalar",
    language: "Til",
    theme: "Mavzu",
    light: "Yorug'",
    dark: "Qorong'u",
    system: "Tizim",
    save: "Saqlash",
    cancel: "Bekor qilish",
    edit: "Tahrirlash",
    delete: "O'chirish",
    confirm: "Tasdiqlash",
    loading: "Yuklanmoqda...",
    error: "Xatolik yuz berdi",
    success: "Muvaffaqiyatli",
    warning: "Ogohlantirish",
    info: "Ma'lumot",
    close: "Yopish",
    open: "Ochish",
    yes: "Ha",
    no: "Yo'q",
    search: "Qidirish",
    filter: "Filtr",
    sort: "Saralash",
    category: "Kategoriya",
    categories: "Kategoriyalar",
    all: "Barchasi",
    popular: "Mashhur",
    new: "Yangi",
    recommended: "Tavsiya etiladi",
    rating: "Reyting",
    reviews: "Sharhlar",
    review: "Sharh",
    addReview: "Sharh qo'shish",
    writeReview: "Sharh yozing",
    submit: "Yuborish",
    back: "Orqaga",
    next: "Keyingi",
    previous: "Oldingi",
    page: "Sahifa",
    of: "dan",
    showing: "Ko'rsatilmoqda",
    results: "natija",
    noResults: "Natija topilmadi",
    tryAgain: "Qayta urinib ko'ring",
    refresh: "Yangilash",
    update: "Yangilash",
    create: "Yaratish",
    add: "Qo'shish",
    remove: "Olib tashlash",
    clear: "Tozalash",
    reset: "Qayta o'rnatish",
    apply: "Qo'llash",
    download: "Yuklab olish",
    upload: "Yuklash",
    import: "Import",
    export: "Export",
    print: "Chop etish",
    share: "Ulashish",
    copy: "Nusxalash",
    paste: "Joylashtirish",
    cut: "Kesish",
    undo: "Bekor qilish",
    redo: "Qaytarish",
    selectAll: "Barchasini tanlash",
    deselectAll: "Tanlovni bekor qilish",
    expand: "Kengaytirish",
    collapse: "Yig'ish",
    fullscreen: "To'liq ekran",
    minimize: "Kichraytirish",
    maximize: "Kattalashtrish",
    restore: "Qaytarish",
    help: "Yordam",
    about: "Haqida",
    version: "Versiya",
    copyright: "Mualliflik huquqi",
    terms: "Shartlar",
    privacy: "Maxfiylik",
    cookies: "Cookie-lar",
    legal: "Huquqiy",
    support: "Qo'llab-quvvatlash",
    feedback: "Fikr-mulohaza",
    report: "Hisobot",
    bug: "Xato",
    feature: "Xususiyat",
    request: "So'rov",
    suggestion: "Taklif",
    improvement: "Yaxshilash",
    enhancement: "Kengaytirish",
    optimization: "Optimallashtirish",
    performance: "Ishlash",
    security: "Xavfsizlik",
    maintenance: "Texnik xizmat",
    update: "Yangilash",
    upgrade: "Yangilash",
    downgrade: "Pasaytirish",
    install: "O'rnatish",
    uninstall: "O'chirish",
    configure: "Sozlash",
    setup: "O'rnatish",
    initialize: "Boshlash",
    start: "Boshlash",
    stop: "To'xtatish",
    pause: "Pauza",
    resume: "Davom ettirish",
    restart: "Qayta boshlash",
    reload: "Qayta yuklash",
    sync: "Sinxronlash",
    backup: "Zaxira nusxa",
    restore: "Qaytarish",
    migrate: "Ko'chirish",
    transfer: "O'tkazish",
    move: "Ko'chirish",
    rename: "Nomini o'zgartirish",
    duplicate: "Nusxalash",
    clone: "Klonlash",
    fork: "Fork",
    merge: "Birlashtirish",
    split: "Bo'lish",
    join: "Qo'shilish",
    leave: "Chiqish",
    invite: "Taklif qilish",
    accept: "Qabul qilish",
    decline: "Rad etish",
    approve: "Tasdiqlash",
    reject: "Rad etish",
    pending: "Kutilmoqda",
    completed: "Tugallandi",
    failed: "Muvaffaqiyatsiz",
    cancelled: "Bekor qilindi",
    expired: "Muddati tugagan",
    active: "Faol",
    inactive: "Nofaol",
    enabled: "Yoqilgan",
    disabled: "O'chirilgan",
    online: "Onlayn",
    offline: "Oflayn",
    available: "Mavjud",
    unavailable: "Mavjud emas",
    inStock: "Omborda bor",
    outOfStock: "Omborda yo'q",
    lowStock: "Kam qoldi",
    unlimited: "Cheksiz",
    limited: "Cheklangan",
    free: "Bepul",
    paid: "Pullik",
    premium: "Premium",
    basic: "Asosiy",
    standard: "Standart",
    advanced: "Ilg'or",
    professional: "Professional",
    enterprise: "Korxona",
    personal: "Shaxsiy",
    business: "Biznes",
    public: "Ommaviy",
    private: "Shaxsiy",
    internal: "Ichki",
    external: "Tashqi",
    local: "Mahalliy",
    remote: "Masofaviy",
    global: "Global",
    regional: "Mintaqaviy",
    national: "Milliy",
    international: "Xalqaro",
    worldwide: "Butun dunyo bo'ylab",
    universal: "Universal",
    general: "Umumiy",
    specific: "Maxsus",
    custom: "Maxsus",
    default: "Standart",
    automatic: "Avtomatik",
    manual: "Qo'lda",
    optional: "Ixtiyoriy",
    required: "Majburiy",
    recommended: "Tavsiya etiladi",
    suggested: "Taklif qilinadi",
    preferred: "Afzal ko'riladi",
    alternative: "Muqobil",
    backup: "Zaxira",
    primary: "Asosiy",
    secondary: "Ikkinchi",
    tertiary: "Uchinchi",
    main: "Asosiy",
    sub: "Pastki",
    parent: "Ota-ona",
    child: "Bola",
    root: "Ildiz",
    branch: "Filial",
    leaf: "Barg",
    node: "Tugun",
    edge: "Chekka",
    vertex: "Cho'qqi",
    graph: "Grafik",
    tree: "Daraxt",
    list: "Ro'yxat",
    table: "Jadval",
    grid: "To'r",
    matrix: "Matritsa",
    array: "Massiv",
    vector: "Vektor",
    scalar: "Skalar",
    object: "Obyekt",
    class: "Sinf",
    instance: "Namuna",
    method: "Usul",
    function: "Funksiya",
    procedure: "Protsedura",
    algorithm: "Algoritm",
    formula: "Formula",
    equation: "Tenglama",
    expression: "Ifoda",
    statement: "Bayonot",
    declaration: "E'lon",
    definition: "Ta'rif",
    implementation: "Amalga oshirish",
    execution: "Bajarish",
    operation: "Operatsiya",
    action: "Harakat",
    task: "Vazifa",
    job: "Ish",
    work: "Ish",
    project: "Loyiha",
    program: "Dastur",
    application: "Ilova",
    software: "Dasturiy ta'minot",
    hardware: "Apparat",
    system: "Tizim",
    platform: "Platforma",
    framework: "Freymvork",
    library: "Kutubxona",
    module: "Modul",
    component: "Komponent",
    element: "Element",
    widget: "Vidjet",
    control: "Boshqaruv",
    interface: "Interfeys",
    api: "API",
    service: "Xizmat",
    resource: "Resurs",
    asset: "Aktiv",
    file: "Fayl",
    folder: "Papka",
    directory: "Katalog",
    path: "Yo'l",
    url: "URL",
    link: "Havola",
    reference: "Ma'lumotnoma",
    pointer: "Ko'rsatkich",
    index: "Indeks",
    key: "Kalit",
    value: "Qiymat",
    pair: "Juft",
    set: "To'plam",
    collection: "Kolleksiya",
    group: "Guruh",
    team: "Jamoa",
    organization: "Tashkilot",
    company: "Kompaniya",
    corporation: "Korporatsiya",
    enterprise: "Korxona",
    business: "Biznes",
    industry: "Sanoat",
    sector: "Sektor",
    market: "Bozor",
    economy: "Iqtisodiyot",
    finance: "Moliya",
    banking: "Bank ishi",
    investment: "Investitsiya",
    trading: "Savdo",
    commerce: "Tijorat",
    retail: "Chakana savdo",
    wholesale: "Ulgurji savdo",
    manufacturing: "Ishlab chiqarish",
    production: "Ishlab chiqarish",
    distribution: "Tarqatish",
    logistics: "Logistika",
    supply: "Ta'minot",
    demand: "Talab",
    customer: "Mijoz",
    client: "Mijoz",
    user: "Foydalanuvchi",
    visitor: "Tashrif buyuruvchi",
    guest: "Mehmon",
    member: "A'zo",
    subscriber: "Obunachi",
    follower: "Kuzatuvchi",
    fan: "Muxlis",
    supporter: "Qo'llab-quvvatlovchi",
    sponsor: "Homiy",
    partner: "Hamkor",
    ally: "Ittifoqchi",
    friend: "Do'st",
    colleague: "Hamkasb",
    teammate: "Jamoadosh",
    competitor: "Raqib",
    rival: "Raqib",
    opponent: "Qarshi tomon",
    enemy: "Dushman",
    stranger: "Notanish",
    acquaintance: "Tanish",
    neighbor: "Qo'shni",
    relative: "Qarindosh",
    family: "Oila",
    parent: "Ota-ona",
    child: "Bola",
    sibling: "Aka-uka/opa-singil",
    spouse: "Turmush o'rtog'i",
    partner: "Sherik",
    lover: "Sevgili",
    boyfriend: "Yigit do'st",
    girlfriend: "Qiz do'st",
    husband: "Er",
    wife: "Xotin",
    son: "O'g'il",
    daughter: "Qiz",
    brother: "Aka/uka",
    sister: "Opa/singil",
    father: "Ota",
    mother: "Ona",
    grandfather: "Bobo",
    grandmother: "Buvi",
    uncle: "Amaki/tog'a",
    aunt: "Xola/amma",
    cousin: "Amakivachcha/xolavachcha",
    nephew: "Jiyani",
    niece: "Jiyani",
    grandchild: "Nevara",
    grandson: "Nevara",
    granddaughter: "Nevara",
    ancestor: "Ajdod",
    descendant: "Avlod",
    generation: "Avlod",
    lineage: "Nasl",
    heritage: "Meros",
    tradition: "An'ana",
    culture: "Madaniyat",
    custom: "Odat",
    habit: "Odat",
    practice: "Amaliyot",
    ritual: "Marosim",
    ceremony: "Tantana",
    celebration: "Bayram",
    festival: "Festival",
    holiday: "Bayram",
    vacation: "Ta'til",
    break: "Tanaffus",
    rest: "Dam olish",
    relaxation: "Dam olish",
    leisure: "Bo'sh vaqt",
    entertainment: "O'yin-kulgi",
    fun: "Qiziq",
    enjoyment: "Zavq",
    pleasure: "Zavq",
    happiness: "Baxt",
    joy: "Quvonch",
    delight: "Xursandchilik",
    satisfaction: "Qoniqish",
    contentment: "Mamnunlik",
    peace: "Tinchlik",
    calm: "Xotirjamlik",
    serenity: "Osoyishtalik",
    tranquility: "Sokinlik",
    quiet: "Jim",
    silence: "Sukunat",
    stillness: "Jimlik",
    motion: "Harakat",
    movement: "Harakat",
    action: "Harakat",
    activity: "Faollik",
    energy: "Energiya",
    power: "Kuch",
    strength: "Kuch",
    force: "Kuch",
    pressure: "Bosim",
    tension: "Kuchlanish",
    stress: "Stress",
    strain: "Zo'riqish",
    effort: "Harakat",
    work: "Ish",
    labor: "Mehnat",
    toil: "Mashaqqat",
    struggle: "Kurash",
    fight: "Jang",
    battle: "Jang",
    war: "Urush",
    conflict: "Mojaro",
    dispute: "Bahs",
    argument: "Bahs",
    debate: "Munozara",
    discussion: "Muhokama",
    conversation: "Suhbat",
    dialogue: "Dialog",
    talk: "Gaplashish",
    speech: "Nutq",
    presentation: "Taqdimot",
    lecture: "Ma'ruza",
    lesson: "Dars",
    class: "Sinf",
    course: "Kurs",
    training: "Trening",
    education: "Ta'lim",
    learning: "O'rganish",
    study: "O'qish",
    research: "Tadqiqot",
    investigation: "Tergov",
    analysis: "Tahlil",
    examination: "Tekshirish",
    inspection: "Nazorat",
    review: "Ko'rib chiqish",
    evaluation: "Baholash",
    assessment: "Baholash",
    test: "Test",
    exam: "Imtihon",
    quiz: "Viktorina",
    question: "Savol",
    answer: "Javob",
    solution: "Yechim",
    problem: "Muammo",
    issue: "Masala",
    challenge: "Qiyinchilik",
    difficulty: "Qiyinchilik",
    obstacle: "To'siq",
    barrier: "To'siq",
    hurdle: "To'siq",
    limitation: "Cheklov",
    restriction: "Cheklov",
    constraint: "Cheklov",
    boundary: "Chegara",
    border: "Chegara",
    edge: "Chekka",
    margin: "Chegara",
    limit: "Chegara",
    maximum: "Maksimal",
    minimum: "Minimal",
    average: "O'rtacha",
    median: "Mediana",
    mode: "Moda",
    range: "Diapazon",
    span: "Oraliq",
    interval: "Interval",
    period: "Davr",
    duration: "Davomiyligi",
    length: "Uzunlik",
    width: "Kenglik",
    height: "Balandlik",
    depth: "Chuqurlik",
    size: "O'lcham",
    dimension: "O'lchov",
    scale: "Miqyos",
    proportion: "Nisbat",
    ratio: "Nisbat",
    percentage: "Foiz",
    fraction: "Kasr",
    decimal: "O'nlik",
    number: "Raqam",
    digit: "Raqam",
    figure: "Raqam",
    amount: "Miqdor",
    quantity: "Miqdor",
    volume: "Hajm",
    capacity: "Sig'im",
    weight: "Og'irlik",
    mass: "Massa",
    density: "Zichlik",
    temperature: "Harorat",
    pressure: "Bosim",
    speed: "Tezlik",
    velocity: "Tezlik",
    acceleration: "Tezlanish",
    frequency: "Chastota",
    wavelength: "To'lqin uzunligi",
    amplitude: "Amplituda",
    phase: "Faza",
    cycle: "Tsikl",
    pattern: "Naqsh",
    sequence: "Ketma-ketlik",
    series: "Qator",
    order: "Tartib",
    arrangement: "Joylashuv",
    organization: "Tashkil etish",
    structure: "Tuzilish",
    format: "Format",
    layout: "Tartib",
    design: "Dizayn",
    style: "Uslub",
    theme: "Mavzu",
    template: "Shablon",
    model: "Model",
    example: "Misol",
    sample: "Namuna",
    specimen: "Namuna",
    prototype: "Prototip",
    draft: "Qoralama",
    sketch: "Eskiz",
    outline: "Kontur",
    plan: "Reja",
    strategy: "Strategiya",
    tactic: "Taktika",
    approach: "Yondashuv",
    method: "Usul",
    technique: "Texnika",
    procedure: "Protsedura",
    process: "Jarayon",
    workflow: "Ish jarayoni",
    pipeline: "Quvur",
    chain: "Zanjir",
    sequence: "Ketma-ketlik",
    step: "Qadam",
    stage: "Bosqich",
    phase: "Faza",
    level: "Daraja",
    grade: "Daraja",
    rank: "Daraja",
    position: "Pozitsiya",
    location: "Joylashuv",
    place: "Joy",
    spot: "Nuqta",
    point: "Nuqta",
    area: "Hudud",
    region: "Mintaqa",
    zone: "Zona",
    sector: "Sektor",
    district: "Tuman",
    neighborhood: "Mahalla",
    community: "Jamiyat",
    society: "Jamiyat",
    population: "Aholi",
    people: "Odamlar",
    person: "Shaxs",
    individual: "Shaxs",
    human: "Inson",
    being: "Mavjudot",
    creature: "Jonzot",
    animal: "Hayvon",
    plant: "O'simlik",
    organism: "Organizm",
    life: "Hayot",
    living: "Tirik",
    alive: "Tirik",
    dead: "O'lik",
    death: "O'lim",
    birth: "Tug'ilish",
    age: "Yosh",
    young: "Yosh",
    old: "Keksa",
    new: "Yangi",
    fresh: "Yangi",
    recent: "Yaqinda",
    current: "Hozirgi",
    present: "Hozir",
    past: "O'tmish",
    future: "Kelajak",
    time: "Vaqt",
    moment: "Lahza",
    instant: "Bir zumda",
    second: "Soniya",
    minute: "Daqiqa",
    hour: "Soat",
    day: "Kun",
    week: "Hafta",
    month: "Oy",
    year: "Yil",
    decade: "O'n yil",
    century: "Asr",
    millennium: "Ming yillik",
    era: "Davr",
    epoch: "Davr",
    age: "Asr",
    period: "Davr",
    season: "Fasl",
    spring: "Bahor",
    summer: "Yoz",
    autumn: "Kuz",
    winter: "Qish",
    weather: "Ob-havo",
    climate: "Iqlim",
    atmosphere: "Atmosfera",
    air: "Havo",
    wind: "Shamol",
    rain: "Yomg'ir",
    snow: "Qor",
    ice: "Muz",
    water: "Suv",
    fire: "Olov",
    earth: "Yer",
    soil: "Tuproq",
    ground: "Yer",
    land: "Yer",
    field: "Dala",
    forest: "O'rmon",
    tree: "Daraxt",
    flower: "Gul",
    grass: "O't",
    mountain: "Tog'",
    hill: "Tepalik",
    valley: "Vodiy",
    river: "Daryo",
    lake: "Ko'l",
    sea: "Dengiz",
    ocean: "Okean",
    beach: "Plyaj",
    shore: "Qirg'oq",
    coast: "Sohil",
    island: "Orol",
    continent: "Qit'a",
    country: "Mamlakat",
    nation: "Millat",
    state: "Davlat",
    government: "Hukumat",
    politics: "Siyosat",
    law: "Qonun",
    rule: "Qoida",
    regulation: "Tartib",
    policy: "Siyosat",
    decision: "Qaror",
    choice: "Tanlov",
    option: "Variant",
    alternative: "Muqobil",
    possibility: "Imkoniyat",
    opportunity: "Imkoniyat",
    chance: "Imkoniyat",
    luck: "Omad",
    fortune: "Boylik",
    wealth: "Boylik",
    money: "Pul",
    currency: "Valyuta",
    coin: "Tanga",
    bill: "Qog'oz pul",
    cash: "Naqd pul",
    credit: "Kredit",
    debt: "Qarz",
    loan: "Qarz",
    interest: "Foiz",
    profit: "Foyda",
    loss: "Zarar",
    gain: "Daromad",
    income: "Daromad",
    salary: "Maosh",
    wage: "Ish haqi",
    payment: "To'lov",
    cost: "Xarajat",
    expense: "Xarajat",
    budget: "Byudjet",
    finance: "Moliya",
    economy: "Iqtisodiyot",
    market: "Bozor",
    trade: "Savdo",
    business: "Biznes",
    company: "Kompaniya",
    corporation: "Korporatsiya",
    organization: "Tashkilot",
    institution: "Muassasa",
    office: "Ofis",
    building: "Bino",
    house: "Uy",
    home: "Uy",
    apartment: "Kvartira",
    room: "Xona",
    kitchen: "Oshxona",
    bedroom: "Yotoq xonasi",
    bathroom: "Hammom",
    living: "Yashash xonasi",
    dining: "Ovqat xonasi",
    garage: "Garaj",
    garden: "Bog'",
    yard: "Hovli",
    street: "Ko'cha",
    road: "Yo'l",
    highway: "Avtomobil yo'li",
    bridge: "Ko'prik",
    tunnel: "Tunnel",
    station: "Stansiya",
    airport: "Aeroport",
    train: "Poyezd",
    bus: "Avtobus",
    car: "Mashina",
    vehicle: "Transport vositasi",
    transportation: "Transport",
    travel: "Sayohat",
    trip: "Sayohat",
    journey: "Safar",
    vacation: "Ta'til",
    holiday: "Bayram",
    tourism: "Turizm",
    tourist: "Sayyoh",
    visitor: "Tashrif buyuruvchi",
    guest: "Mehmon",
    hotel: "Mehmonxona",
    restaurant: "Restoran",
    cafe: "Kafe",
    bar: "Bar",
    club: "Klub",
    theater: "Teatr",
    cinema: "Kino",
    museum: "Muzey",
    library: "Kutubxona",
    school: "Maktab",
    university: "Universitet",
    college: "Kollej",
    hospital: "Kasalxona",
    clinic: "Klinika",
    doctor: "Shifokor",
    nurse: "Hamshira",
    patient: "Bemor",
    medicine: "Dori",
    health: "Salomatlik",
    disease: "Kasallik",
    illness: "Kasallik",
    injury: "Jarohat",
    pain: "Og'riq",
    treatment: "Davolash",
    cure: "Davo",
    therapy: "Terapiya",
    surgery: "Jarrohlik",
    operation: "Operatsiya",
    examination: "Ko'rik",
    diagnosis: "Tashxis",
    symptom: "Alomat",
    recovery: "Tuzalish",
    healing: "Shifo",
    wellness: "Farovonlik",
    fitness: "Jismoniy tayyorgarlik",
    exercise: "Mashq",
    sport: "Sport",
    game: "O'yin",
    play: "O'ynash",
    competition: "Musobaqa",
    contest: "Tanlov",
    match: "O'yin",
    tournament: "Turnir",
    championship: "Chempionat",
    victory: "G'alaba",
    defeat: "Mag'lubiyat",
    win: "G'alaba",
    lose: "Yutqazish",
    draw: "Durrang",
    tie: "Durrang",
    score: "Hisob",
    point: "Ochko",
    goal: "Gol",
    target: "Maqsad",
    objective: "Maqsad",
    purpose: "Maqsad",
    aim: "Maqsad",
    intention: "Niyat",
    plan: "Reja",
    idea: "G'oya",
    thought: "Fikr",
    concept: "Kontseptsiya",
    notion: "Tushuncha",
    understanding: "Tushunish",
    knowledge: "Bilim",
    information: "Ma'lumot",
    data: "Ma'lumot",
    fact: "Fakt",
    truth: "Haqiqat",
    reality: "Haqiqat",
    fiction: "Fantastika",
    story: "Hikoya",
    tale: "Ertak",
    legend: "Afsona",
    myth: "Mif",
    history: "Tarix",
    past: "O'tmish",
    present: "Hozir",
    future: "Kelajak",
    tomorrow: "Ertaga",
    yesterday: "Kecha",
    today: "Bugun",
    now: "Hozir",
    then: "O'shanda",
    when: "Qachon",
    where: "Qayerda",
    what: "Nima",
    who: "Kim",
    why: "Nega",
    how: "Qanday",
    which: "Qaysi",
    whose: "Kimning",
    whom: "Kimga",
    this: "Bu",
    that: "U",
    these: "Bular",
    those: "Ular",
    here: "Bu yerda",
    there: "U yerda",
    everywhere: "Hamma joyda",
    nowhere: "Hech qayerda",
    somewhere: "Biror joyda",
    anywhere: "Istalgan joyda",
    everyone: "Hamma",
    nobody: "Hech kim",
    somebody: "Kimdir",
    anybody: "Har kim",
    everything: "Hamma narsa",
    nothing: "Hech narsa",
    something: "Biror narsa",
    anything: "Har qanday narsa",
    always: "Doimo",
    never: "Hech qachon",
    sometimes: "Ba'zan",
    often: "Tez-tez",
    rarely: "Kamdan-kam",
    usually: "Odatda",
    normally: "Odatda",
    generally: "Umuman",
    specifically: "Aniq",
    particularly: "Ayniqsa",
    especially: "Ayniqsa",
    mainly: "Asosan",
    mostly: "Ko'pincha",
    partly: "Qisman",
    completely: "To'liq",
    totally: "Butunlay",
    entirely: "Butunlay",
    fully: "To'liq",
    partially: "Qisman",
    hardly: "Deyarli",
    barely: "Zo'rg'a",
    almost: "Deyarli",
    nearly: "Deyarli",
    quite: "Ancha",
    rather: "Ancha",
    very: "Juda",
    extremely: "Juda",
    incredibly: "Ajoyib",
    amazingly: "Hayratlanarli",
    surprisingly: "Hayratlanarli",
    obviously: "Aniq",
    clearly: "Aniq",
    definitely: "Albatta",
    certainly: "Albatta",
    surely: "Albatta",
    probably: "Ehtimol",
    possibly: "Mumkin",
    maybe: "Balki",
    perhaps: "Balki",
    likely: "Ehtimol",
    unlikely: "Ehtimol emas",
    impossible: "Imkonsiz",
    possible: "Mumkin",
    necessary: "Zarur",
    unnecessary: "Keraksiz",
    important: "Muhim",
    unimportant: "Muhim emas",
    significant: "Muhim",
    insignificant: "Ahamiyatsiz",
    relevant: "Tegishli",
    irrelevant: "Tegishli emas",
    useful: "Foydali",
    useless: "Foydasiz",
    helpful: "Yordam beruvchi",
    harmful: "Zararli",
    beneficial: "Foydali",
    dangerous: "Xavfli",
    safe: "Xavfsiz",
    secure: "Xavfsiz",
    risky: "Xavfli",
    certain: "Aniq",
    uncertain: "Noaniq",
    sure: "Ishonchli",
    unsure: "Ishonchsiz",
    confident: "Ishonchli",
    doubtful: "Shubhali",
    positive: "Ijobiy",
    negative: "Salbiy",
    neutral: "Neytral",
    good: "Yaxshi",
    bad: "Yomon",
    excellent: "A'lo",
    poor: "Yomon",
    great: "Ajoyib",
    terrible: "Dahshatli",
    wonderful: "Ajoyib",
    awful: "Dahshatli",
    amazing: "Hayratlanarli",
    horrible: "Dahshatli",
    fantastic: "Fantastik",
    dreadful: "Qo'rqinchli",
    marvelous: "Ajoyib",
    disgusting: "Jirkanch",
    beautiful: "Chiroyli",
    ugly: "Xunuk",
    attractive: "Jozibali",
    repulsive: "Jirkanch",
    pretty: "Chiroyli",
    plain: "Oddiy",
    handsome: "Kelishgan",
    cute: "Yoqimli",
    lovely: "Yoqimli",
    charming: "Maftunkor",
    elegant: "Nafis",
    graceful: "Nafis",
    stylish: "Zamonaviy",
    fashionable: "Moda",
    trendy: "Zamonaviy",
    modern: "Zamonaviy",
    contemporary: "Zamonaviy",
    traditional: "An'anaviy",
    classic: "Klassik",
    vintage: "Eski uslub",
    antique: "Antik",
    ancient: "Qadimiy",
    old: "Eski",
    new: "Yangi",
    fresh: "Yangi",
    recent: "Yaqinda",
    latest: "Eng so'nggi",
    current: "Hozirgi",
    updated: "Yangilangan",
    outdated: "Eskirgan",
    obsolete: "Eskirgan",
    advanced: "Ilg'or",
    sophisticated: "Murakkab",
    complex: "Murakkab",
    complicated: "Murakkab",
    simple: "Oddiy",
    easy: "Oson",
    difficult: "Qiyin",
    hard: "Qiyin",
    challenging: "Qiyinchilik",
    tough: "Qattiq",
    soft: "Yumshoq",
    smooth: "Silliq",
    rough: "Qo'pol",
    sharp: "O'tkir",
    dull: "To'mtoq",
    bright: "Yorqin",
    dark: "Qorong'i",
    light: "Yorug'",
    heavy: "Og'ir",
    light: "Yengil",
    big: "Katta",
    small: "Kichik",
    large: "Katta",
    tiny: "Juda kichik",
    huge: "Ulkan",
    enormous: "Juda katta",
    giant: "Gigant",
    massive: "Katta",
    miniature: "Kichik",
    wide: "Keng",
    narrow: "Tor",
    broad: "Keng",
    thin: "Yupqa",
    thick: "Qalin",
    tall: "Baland",
    short: "Past",
    high: "Baland",
    low: "Past",
    deep: "Chuqur",
    shallow: "Sayoz",
    long: "Uzun",
    brief: "Qisqa",
    quick: "Tez",
    slow: "Sekin",
    fast: "Tez",
    rapid: "Tez",
    swift: "Tez",
    gradual: "Asta-sekin",
    sudden: "To'satdan",
    immediate: "Darhol",
    instant: "Bir zumda",
    delayed: "Kechiktirilgan",
    early: "Erta",
    late: "Kech",
    on: "Ustida",
    off: "O'chirilgan",
    up: "Yuqoriga",
    down: "Pastga",
    in: "Ichida",
    out: "Tashqarida",
    inside: "Ichkarida",
    outside: "Tashqarida",
    above: "Ustida",
    below: "Ostida",
    over: "Ustidan",
    under: "Ostidan",
    before: "Oldin",
    after: "Keyin",
    during: "Davomida",
    while: "Paytida",
    until: "Gacha",
    since: "Dan beri",
    from: "Dan",
    to: "Ga",
    for: "Uchun",
    with: "Bilan",
    without: "Siz",
    by: "Tomonidan",
    through: "Orqali",
    across: "Bo'ylab",
    along: "Bo'ylab",
    around: "Atrofida",
    near: "Yaqinida",
    far: "Uzoqda",
    close: "Yaqin",
    distant: "Uzoq",
    between: "Orasida",
    among: "Orasida",
    within: "Ichida",
    beyond: "Orqasida",
    against: "Qarshi",
    towards: "Tomon",
    away: "Uzoqda",
    forward: "Oldinga",
    backward: "Orqaga",
    left: "Chap",
    right: "O'ng",
    straight: "To'g'ri",
    curved: "Egri",
    round: "Dumaloq",
    square: "Kvadrat",
    rectangular: "To'rtburchak",
    triangular: "Uchburchak",
    circular: "Dumaloq",
    oval: "Oval",
    flat: "Tekis",
    solid: "Qattiq",
    liquid: "Suyuq",
    gas: "Gaz",
    hot: "Issiq",
    cold: "Sovuq",
    warm: "Iliq",
    cool: "Salqin",
    freezing: "Muzlatuvchi",
    boiling: "Qaynatuvchi",
    wet: "Ho'l",
    dry: "Quruq",
    clean: "Toza",
    dirty: "Iflos",
    pure: "Sof",
    mixed: "Aralash",
    full: "To'la",
    empty: "Bo'sh",
    half: "Yarim",
    whole: "Butun",
    part: "Qism",
    piece: "Bo'lak",
    bit: "Parcha",
    fragment: "Parcha",
    section: "Bo'lim",
    portion: "Qism",
    share: "Ulush",
    division: "Bo'linish",
    unit: "Birlik",
    single: "Yagona",
    double: "Ikki marta",
    triple: "Uch marta",
    multiple: "Ko'p",
    several: "Bir necha",
    many: "Ko'p",
    few: "Oz",
    little: "Kichik",
    much: "Ko'p",
    more: "Ko'proq",
    less: "Kamroq",
    most: "Eng ko'p",
    least: "Eng kam",
    all: "Hammasi",
    none: "Hech biri",
    some: "Ba'zi",
    any: "Har qanday",
    each: "Har bir",
    every: "Har",
    both: "Ikkalasi ham",
    either: "Ikkalasidan biri",
    neither: "Ikkalasi ham emas",
    first: "Birinchi",
    second: "Ikkinchi",
    third: "Uchinchi",
    last: "Oxirgi",
    final: "Yakuniy",
    initial: "Boshlang'ich",
    beginning: "Boshlanish",
    start: "Boshlash",
    end: "Tugash",
    finish: "Tugatish",
    complete: "To'liq",
    incomplete: "To'liq emas",
    perfect: "Mukammal",
    imperfect: "Nomukammal",
    correct: "To'g'ri",
    incorrect: "Noto'g'ri",
    right: "To'g'ri",
    wrong: "Noto'g'ri",
    true: "Haqiqiy",
    false: "Yolg'on",
    real: "Haqiqiy",
    fake: "Soxta",
    genuine: "Haqiqiy",
    artificial: "Sun'iy",
    natural: "Tabiiy",
    synthetic: "Sintetik",
    organic: "Organik",
    chemical: "Kimyoviy",
    physical: "Jismoniy",
    mental: "Aqliy",
    emotional: "Hissiy",
    spiritual: "Ruhiy",
    social: "Ijtimoiy",
    cultural: "Madaniy",
    political: "Siyosiy",
    economic: "Iqtisodiy",
    financial: "Moliyaviy",
    commercial: "Tijorat",
    industrial: "Sanoat",
    agricultural: "Qishloq xo'jaligi",
    educational: "Ta'lim",
    medical: "Tibbiy",
    legal: "Huquqiy",
    technical: "Texnik",
    scientific: "Ilmiy",
    artistic: "San'at",
    creative: "Ijodiy",
    innovative: "Innovatsion",
    traditional: "An'anaviy",
    conventional: "An'anaviy",
    alternative: "Muqobil",
    optional: "Ixtiyoriy",
    mandatory: "Majburiy",
    voluntary: "Ixtiyoriy",
    automatic: "Avtomatik",
    manual: "Qo'lda",
    digital: "Raqamli",
    analog: "Analog",
    electronic: "Elektron",
    mechanical: "Mexanik",
    electrical: "Elektr",
    magnetic: "Magnit",
    optical: "Optik",
    acoustic: "Akustik",
    thermal: "Issiqlik",
    nuclear: "Yadro",
    solar: "Quyosh",
    lunar: "Oy",
    stellar: "Yulduz",
    planetary: "Sayyora",
    cosmic: "Koinot",
    universal: "Universal",
    global: "Global",
    international: "Xalqaro",
    national: "Milliy",
    regional: "Mintaqaviy",
    local: "Mahalliy",
    personal: "Shaxsiy",
    private: "Shaxsiy",
    public: "Ommaviy",
    official: "Rasmiy",
    unofficial: "Norasmiy",
    formal: "Rasmiy",
    informal: "Norasmiy",
    professional: "Professional",
    amateur: "Havaskor",
    expert: "Mutaxassis",
    specialist: "Mutaxassis",
    beginner: "Boshlang'ich",
    advanced: "Ilg'or",
    experienced: "Tajribali",
    skilled: "Malakali",
    talented: "Iqtidorli",
    gifted: "Iste'dodli",
    capable: "Qobiliyatli",
    competent: "Layoqatli",
    qualified: "Malakali",
    certified: "Sertifikatlangan",
    licensed: "Litsenziyali",
    authorized: "Vakolatlangan",
    approved: "Tasdiqlangan",
    verified: "Tekshirilgan",
    validated: "Tasdiqlangan",
    confirmed: "Tasdiqlangan",
    accepted: "Qabul qilingan",
    rejected: "Rad etilgan",
    denied: "Rad etilgan",
    refused: "Rad etilgan",
    declined: "Rad etilgan",
    cancelled: "Bekor qilingan",
    postponed: "Kechiktirilgan",
    delayed: "Kechiktirilgan",
    scheduled: "Rejalashtirilgan",
    planned: "Rejalashtirilgan",
    organized: "Tashkil etilgan",
    arranged: "Tartibga solingan",
    prepared: "Tayyorlangan",
    ready: "Tayyor",
    finished: "Tugallangan",
    completed: "Bajarilgan",
    done: "Bajarilgan",
    undone: "Bajarilmagan",
    pending: "Kutilmoqda",
    processing: "Qayta ishlanmoqda",
    working: "Ishlamoqda",
    running: "Ishlamoqda",
    stopped: "To'xtatilgan",
    paused: "Pauza qilingan",
    resumed: "Davom ettirilgan",
    restarted: "Qayta boshlangan",
    reset: "Qayta o'rnatilgan",
    cleared: "Tozalangan",
    deleted: "O'chirilgan",
    removed: "Olib tashlangan",
    added: "Qo'shilgan",
    inserted: "Kiritilgan",
    updated: "Yangilangan",
    modified: "O'zgartirilgan",
    changed: "O'zgartirilgan",
    edited: "Tahrirlangan",
    revised: "Qayta ko'rib chiqilgan",
    improved: "Yaxshilangan",
    enhanced: "Kuchaytirilgan",
    upgraded: "Yangilangan",
    downgraded: "Pasaytirilgan",
    installed: "O'rnatilgan",
    uninstalled: "O'chirilgan",
    configured: "Sozlangan",
    setup: "O'rnatilgan",
    initialized: "Boshlangan",
    launched: "Ishga tushirilgan",
    deployed: "Joylashtirgan",
    published: "Nashr etilgan",
    released: "Chiqarilgan",
    distributed: "Tarqatilgan",
    delivered: "Yetkazilgan",
    shipped: "Jo'natilgan",
    received: "Qabul qilingan",
    obtained: "Olingan",
    acquired: "Sotib olingan",
    purchased: "Sotib olingan",
    sold: "Sotilgan",
    bought: "Sotib olingan",
    rented: "Ijaraga olingan",
    leased: "Ijaraga berilgan",
    borrowed: "Qarzga olingan",
    lent: "Qarzga berilgan",
    given: "Berilgan",
    taken: "Olingan",
    sent: "Yuborilgan",
    received: "Qabul qilingan",
    transferred: "O'tkazilgan",
    moved: "Ko'chirilgan",
    copied: "Nusxalangan",
    duplicated: "Takrorlangan",
    replicated: "Takrorlangan",
    cloned: "Klonlangan",
    backed: "Zaxiralangan",
    restored: "Qaytarilgan",
    recovered: "Tiklanilgan",
    repaired: "Ta'mirlangan",
    fixed: "Tuzatilgan",
    broken: "Buzilgan",
    damaged: "Shikastlangan",
    destroyed: "Vayron qilingan",
    created: "Yaratilgan",
    built: "Qurilgan",
    constructed: "Qurilgan",
    developed: "Ishlab chiqilgan",
    designed: "Loyihalashtirilgan",
    planned: "Rejalashtirilgan",
    drafted: "Loyihalashtirilgan",
    sketched: "Chizilgan",
    drawn: "Chizilgan",
    painted: "Bo'yalgan",
    colored: "Ranglangan",
    decorated: "Bezatilgan",
    furnished: "Jihozlangan",
    equipped: "Jihozlangan",
    supplied: "Ta'minlangan",
    provided: "Ta'minlangan",
    offered: "Taklif qilingan",
    suggested: "Taklif qilingan",
    recommended: "Tavsiya etilgan",
    advised: "Maslahat berilgan",
    warned: "Ogohlantirgan",
    informed: "Xabardor qilingan",
    notified: "Xabardor qilingan",
    alerted: "Ogohlantirgan",
    reminded: "Eslatilgan",
    told: "Aytilgan",
    said: "Aytilgan",
    spoken: "Gapirgan",
    talked: "Gaplashgan",
    discussed: "Muhokama qilingan",
    debated: "Munozara qilingan",
    argued: "Bahslashgan",
    agreed: "Kelishgan",
    disagreed: "Kelishmagan",
    accepted: "Qabul qilgan",
    rejected: "Rad etgan",
    approved: "Tasdiqlagan",
    denied: "Rad etgan",
    allowed: "Ruxsat bergan",
    permitted: "Ruxsat bergan",
    forbidden: "Taqiqlangan",
    prohibited: "Taqiqlangan",
    banned: "Taqiqlangan",
    restricted: "Cheklangan",
    limited: "Cheklangan",
    unlimited: "Cheksiz",
    free: "Erkin",
    open: "Ochiq",
    closed: "Yopiq",
    locked: "Qulflangan",
    unlocked: "Qulfdan ochilgan",
    secured: "Himoyalangan",
    protected: "Himoyalangan",
    defended: "Himoya qilingan",
    attacked: "Hujum qilingan",
    invaded: "Bostirib kirilgan",
    occupied: "Egallab olingan",
    conquered: "Zabt etilgan",
    defeated: "Mag'lub etilgan",
    won: "G'alaba qozongan",
    lost: "Yutqazgan",
    tied: "Durrang",
    drawn: "Durrang",
    succeeded: "Muvaffaq bo'lgan",
    failed: "Muvaffaqiyatsiz",
    passed: "O'tgan",
    failed: "Muvaffaqiyatsiz",
    graduated: "Bitirgan",
    promoted: "Ko'tarilgan",
    demoted: "Tushirilgan",
    hired: "Ishga olingan",
    fired: "Ishdan bo'shatilgan",
    resigned: "Iste'fo bergan",
    retired: "Nafaqaga chiqqan",
    worked: "Ishlagan",
    employed: "Ishga olingan",
    unemployed: "Ishsiz",
    jobless: "Ishsiz",
    busy: "Band",
    free: "Bo'sh",
    available: "Mavjud",
    occupied: "Band",
    engaged: "Band",
    married: "Turmushga chiqqan",
    single: "Bo'ydoq",
    divorced: "Ajrashgan",
    widowed: "Beva",
    separated: "Ajralgan",
    together: "Birga",
    apart: "Alohida",
    united: "Birlashgan",
    divided: "Bo'lingan",
    connected: "Bog'langan",
    disconnected: "Uzilgan",
    linked: "Bog'langan",
    unlinked: "Uzilgan",
    joined: "Qo'shilgan",
    separated: "Ajralgan",
    combined: "Birlashtirilgan",
    mixed: "Aralashtirilgan",
    blended: "Aralashtirilgan",
    merged: "Birlashtirilgan",
    split: "Bo'lingan",
    divided: "Bo'lingan",
    shared: "Baham ko'rilgan",
    distributed: "Taqsimlangan",
    allocated: "Ajratilgan",
    assigned: "Tayinlangan",
    appointed: "Tayinlangan",
    selected: "Tanlangan",
    chosen: "Tanlangan",
    picked: "Tanlangan",
    elected: "Saylangan",
    voted: "Ovoz bergan",
    decided: "Qaror qilgan",
    determined: "Aniqlagan",
    resolved: "Hal qilgan",
    solved: "Yechgan",
    answered: "Javob bergan",
    responded: "Javob bergan",
    replied: "Javob bergan",
    reacted: "Munosabat bildirgan",
    behaved: "O'zini tutgan",
    acted: "Harakat qilgan",
    performed: "Bajargan",
    executed: "Bajargan",
    implemented: "Amalga oshirgan",
    applied: "Qo'llagan",
    used: "Ishlatgan",
    utilized: "Foydalangan",
    employed: "Ishlatgan",
    operated: "Boshqargan",
    controlled: "Nazorat qilgan",
    managed: "Boshqargan",
    supervised: "Nazorat qilgan",
    monitored: "Kuzatgan",
    observed: "Kuzatgan",
    watched: "Tomosha qilgan",
    looked: "Qaragan",
    seen: "Ko'rgan",
    viewed: "Ko'rgan",
    noticed: "Sezgan",
    spotted: "Ko'rgan",
    detected: "Aniqlagan",
    discovered: "Kashf etgan",
    found: "Topgan",
    located: "Joylashgan",
    positioned: "Joylashtirilgan",
    placed: "Qo'yilgan",
    put: "Qo'ygan",
    set: "O'rnatgan",
    installed: "O'rnatgan",
    mounted: "O'rnatgan",
    attached: "Biriktirilgan",
    connected: "Ulangan",
    plugged: "Ulangan",
    unplugged: "Uzilgan",
    detached: "Ajratilgan",
    removed: "Olib tashlangan",
    taken: "Olingan",
    brought: "Olib kelgan",
    carried: "Ko'targan",
    lifted: "Ko'targan",
    raised: "Ko'targan",
    lowered: "Tushirgan",
    dropped: "Tashlab yuborgan",
    fell: "Yiqilgan",
    fallen: "Yiqilgan",
    rose: "Ko'tarilgan",
    risen: "Ko'tarilgan",
    climbed: "Chiqgan",
    descended: "Tushgan",
    ascended: "Ko'tarilgan",
    jumped: "Sakragan",
    leaped: "Sakragan",
    hopped: "Sakragan",
    skipped: "Sakragan",
    ran: "Yugurgan",
    walked: "Yurgan",
    moved: "Harakat qilgan",
    traveled: "Sayohat qilgan",
    journeyed: "Safar qilgan",
    went: "Borgan",
    came: "Kelgan",
    arrived: "Yetib kelgan",
    departed: "Jo'nagan",
    left: "Ketgan",
    stayed: "Qolgan",
    remained: "Qolgan",
    continued: "Davom etgan",
    stopped: "To'xtagan",
    paused: "Pauza qilgan",
    waited: "Kutgan",
    expected: "Kutgan",
    anticipated: "Kutgan",
    hoped: "Umid qilgan",
    wished: "Xohlaganlar",
    wanted: "Xohlagan",
    desired: "Xohlagan",
    needed: "Kerak bo'lgan",
    required: "Talab qilingan",
    demanded: "Talab qilgan",
    requested: "So'ragan",
    asked: "So'ragan",
    questioned: "Savol bergan",
    inquired: "So'ragan",
    investigated: "Tekshirgan",
    researched: "Tadqiq qilgan",
    studied: "O'rgangan",
    learned: "O'rgangan",
    taught: "O'rgatgan",
    educated: "Ta'lim bergan",
    trained: "Mashq qildirgan",
    practiced: "Mashq qilgan",
    exercised: "Mashq qilgan",
    played: "O'ynagan",
    enjoyed: "Zavqlangan",
    liked: "Yoqtirgan",
    loved: "Sevgan",
    adored: "Sevgan",
    hated: "Yomon ko'rgan",
    disliked: "Yoqtirmagan",
    preferred: "Afzal ko'rgan",
    favored: "Afzal ko'rgan",
    chose: "Tanlagan",
    selected: "Tanlangan",
    picked: "Tanlangan",
    decided: "Qaror qilgan",
    concluded: "Xulosa chiqargan",
    finished: "Tugatgan",
    ended: "Tugagan",
    started: "Boshlagan",
    began: "Boshlagan",
    initiated: "Boshlagan",
    launched: "Ishga tushirgan",
    opened: "Ochgan",
    closed: "Yopgan",
    shut: "Yopgan",
    locked: "Qulflagan",
    unlocked: "Qulfdan ochgan",
    entered: "Kirgan",
    exited: "Chiqgan",
    left: "Ketgan",
    returned: "Qaytgan",
    came: "Kelgan",
    went: "Borgan",
  },
  ru: {
    home: "Главная",
    menu: "Меню",
    cart: "Корзина",
    contact: "Контакты",
    about: "О нас",
    admin: "Админ",
    login: "Войти",
    register: "Регистрация",
    logout: "Выйти",
    addToCart: "В корзину",
    order: "Заказать",
    total: "Итого",
    welcome: "Добро пожаловать в Milano Cafe",
    ourMenu: "Наше меню",
    specialOffers: "Специальные предложения",
    aboutUs: "О нас",
    contactUs: "Свяжитесь с нами",
    address: "Адрес",
    phone: "Телефон",
    email: "Email",
    workingHours: "Часы работы",
    monday: "Понедельник",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    sunday: "Воскресенье",
    orderSuccess: "Заказ успешно отправлен!",
    orderConfirmed: "Заказ подтвержден",
    processing: "Готовится",
    ready: "Готов",
    delivered: "Доставлен",
    quantity: "Количество",
    price: "Цена",
    recipe: "Рецепт",
    ingredients: "Состав",
    name: "Имя",
    message: "Сообщение",
    send: "Отправить",
    location: "Местоположение",
    selectLocation: "Выберите местоположение",
    paymentMethod: "Способ оплаты",
    cash: "Наличные",
    card: "Карта",
    click: "Click",
    payme: "Payme",
    confirmOrder: "Подтвердить заказ",
    orderPlaced: "Заказ принят",
    thankYou: "Спасибо!",
    account: "Аккаунт",
    myOrders: "Мои заказы",
    orderHistory: "История заказов",
    profile: "Профиль",
    settings: "Настройки",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Темная",
    system: "Системная",
    save: "Сохранить",
    cancel: "Отмена",
    edit: "Редактировать",
    delete: "Удалить",
    confirm: "Подтвердить",
    loading: "Загрузка...",
    error: "Произошла ошибка",
    success: "Успешно",
    warning: "Предупреждение",
    info: "Информация",
    close: "Закрыть",
    open: "Открыть",
    yes: "Да",
    no: "Нет",
    search: "Поиск",
    filter: "Фильтр",
    sort: "Сортировка",
    category: "Категория",
    categories: "Категории",
    all: "Все",
    popular: "Популярное",
    new: "Новое",
    recommended: "Рекомендуемое",
  },
  en: {
    home: "Home",
    menu: "Menu",
    cart: "Cart",
    contact: "Contact",
    about: "About Us",
    admin: "Admin",
    login: "Login",
    register: "Register",
    logout: "Logout",
    addToCart: "Add to Cart",
    order: "Order",
    total: "Total",
    welcome: "Welcome to Milano Cafe",
    ourMenu: "Our Menu",
    specialOffers: "Special Offers",
    aboutUs: "About Us",
    contactUs: "Contact Us",
    address: "Address",
    phone: "Phone",
    email: "Email",
    workingHours: "Working Hours",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    orderSuccess: "Order sent successfully!",
    orderConfirmed: "Order confirmed",
    processing: "Processing",
    ready: "Ready",
    delivered: "Delivered",
    quantity: "Quantity",
    price: "Price",
    recipe: "Recipe",
    ingredients: "Ingredients",
    name: "Name",
    message: "Message",
    send: "Send",
    location: "Location",
    selectLocation: "Select Location",
    paymentMethod: "Payment Method",
    cash: "Cash",
    card: "Card",
    click: "Click",
    payme: "Payme",
    confirmOrder: "Confirm Order",
    orderPlaced: "Order Placed",
    thankYou: "Thank You!",
    account: "Account",
    myOrders: "My Orders",
    orderHistory: "Order History",
    profile: "Profile",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "Loading...",
    error: "An error occurred",
    success: "Success",
    warning: "Warning",
    info: "Information",
    close: "Close",
    open: "Open",
    yes: "Yes",
    no: "No",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    category: "Category",
    categories: "Categories",
    all: "All",
    popular: "Popular",
    new: "New",
    recommended: "Recommended",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("uz")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["uz", "ru", "en"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
